#!/bin/sh
### BEGIN INIT INFO
# Provides:		lsb-dtlogin
# Required-Start:	$all
# Required-Stop:	
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Dtlogin
# Description:		Dtlogin
### END INIT INFO

export PATH="/usr/dt/bin:$PATH"
OPTIONS="-quiet -daemon"
DAEMON=/usr/dt/bin/dtlogin

if [ -r /etc/default/locale ]; then
        . /etc/default/locale
        export LANG
fi

start(){
	if [ -z "$(pidof $DAEMON)" ];
	then
		echo " * Starting dtlogin..."
		$DAEMON $OPTIONS
	fi
}

stop(){
	if [ -n "$(pidof $DAEMON)" ];
	then
		echo " * Stopping dtlogin..."
		kill $(pidof $DAEMON)
		sleep 1
		if [ -n "$(pidof $DAEMON)" ]; then
			echo " * dtlogin refused to stop, killing..."
			kill -9 $(pidof $DAEMON)
		fi
	fi
}

case "$1" in
	'start')
		start
	;;
	'stop')
		stop
	;;
	'restart')
		stop
		start
	;;
	'status')
		if [ -z "$(pidof $DAEMON)" ];
		then
			echo "DTlogin is not currently running..."
			exit 3
		else
			echo "DTlogin is running..." && echo "[ $(pidof dtlogin) ]"
			exit 0
		fi
	;;
	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 0
	;;
esac
